[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cell2cell"
version = "0.0.1"
requires-python = ">=3.11"
dynamic = ["dependencies"]

[tool.setuptools]
packages = {find = {}}
include-package-data = true
